config/routes.rb
Rails.application.routes.draw do

  root to: 'opens#top'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do 
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resources :went_to_gos, only: [:index]
  end
  resources :comments
  resources :places do
    resources :posts, only: [:new]
    resources :went_to_gos, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :posts
  # has_many :tag_for_palaces
  # belongs_to :category
  has_many :went_to_gos

  mount_uploaders :images, ImageUploader

   # 引数ユーザがこの場所に対して行ってみたいしてれば、そのwent_to_go_userを返す
  def went_to_go_user(user_id)
    went_to_gos.find_by(user_id: user_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable

  has_many :likes
  has_many :comments
  # has_many :tag_for_posts
  # has_many :equipments
  belongs_to :place
  belongs_to :user

  # 引数ユーザがこの投稿に対していいねしてるか
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  mount_uploaders :images, ImageUploader

  # バリデーション
  validates :title, presence: true
  validates :title, length: { in: 1..30 } 

  validates :user_id, presence: true
  validates :place_id, presence: true
  validates :images, presence: true
  validates :title, presence: true
  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"

  validates :following_id, presence: true
  validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :went_to_gos, dependent: :destroy

  has_many :following_relationships,foreign_key: "follower_id", class_name: "FollowRelationship",  dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships,foreign_key: "following_id",class_name: "FollowRelationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    self.followings.include?(other_user)
  end

  mount_uploader :profile_image, ImageUploader
  mount_uploader :back_image, ImageUploader

  # バリデーション
  validates :name, length: { in: 1..15 }

  validates :account_name, presence: true
  validates :account_name, format: { with: /\A[0-9a-zA-Z]+\z/ }
  validates :account_name, presence: true
  validates :account_name, uniqueness: true
  validates :account_name, length: { in: 1..15 } 


end

app/models/went_to_go.rb
class WentToGo < ApplicationRecord
  belongs_to :place
  belongs_to :user
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/opens_controller.rb
class OpensController < ApplicationController
  def top
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @places = Place.all
    @place = Place.find(params[:place_id])
    @post.place_id = @place.id
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      @place = @post.place
      @places = Place.all
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])

    # 投稿したユーザでない場合は更新不可
    if @post.user != current_user
      redirect_to user_path(current_user)
    end

    # 投稿のあるPlaceのみ
    @places = Place.all
    array = []
    @places.each do |place|
      array.push(place.id) if place.posts.present?
    end
    @places = @places.where(id: array)

    @place = @post.place
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      # 投稿のあるPlaceのみ
      @places = Place.all
      array = []
      @places.each do |place|
        array.push(place.id) if place.posts.present?
      end
      @places = @places.where(id: array)

      @place = @post.place

      render "edit"
    end
    
  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit(:title, :user_id, :place_id, :comment, :date, :time, :rate, :access, :notify, :url, :camera, :tag_list, {images: []})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    
    @like_count_array = @user.posts.map{|post| post.likes.count}
    @like_count = @like_count_array.sum
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end

  def followings
    @user =User.find(params[:id])
    @users =@user.followings.page(params[:page]).per(5)
    render 'show_followings'
  end

  def followers
    @user =User.find(params[:id])
    @users =@user.followers.page(params[:page]).per(5)
    render 'show_followers'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :address, :is_admin, :back_image)
  end
end

app/controllers/went_to_gos_controller.rb
class WentToGosController < ApplicationController

  before_action :authenticate_user!
  before_action :set_place

  # 行ってみたいスポット
  def index
    @user = User.find(params[:user_id])
    went_to_gos = @user.went_to_gos
    @places = Place.where(id: went_to_gos.map{|go| go.place_id})

    @posts_data_arr = []
    @places.each do |place|
      @posts_data_arr.push({:id => place.id, :name => place.name, :lat => place.latitude, :lng => place.longitude})
    end
    @posts_data_json = @posts_data_arr.to_json.html_safe
  end

  def create
    @went_to_go = WentToGo.create(user_id: current_user.id, place_id: params[:place_id])
    @went_to_gos = WentToGo.where(place_id: params[:place_id])
    @place.reload
  end

  def destroy
    went_to_go = WentToGo.find_by(user_id: current_user.id, place_id: params[:place_id])
    went_to_go.destroy
    @went_to_gos = WentToGo.where(place_id: params[:place_id])
    @place.reload
  end

  private

  def set_place
    @place = Place.find_by(id: params[:place_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opens_helper.rb
module OpensHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/went_to_gos_helper.rb
module WentToGosHelper
end

app/views/went_to_gos/_went_to_go.html.erb
<% if user_signed_in? %>

  <% unless place.went_to_go_user(current_user.id).blank? %>
    <%= link_to place_went_to_go_path(place_id: place.id, id: place.went_to_go_user(current_user.id)), method: :delete, remote: true do %>
      <div class="vertical_like">
        <i class="fas fa-map"></i>
        <span class="red-text">
          <%= place.went_to_gos.count %>
        </span>
      </div>
    <% end %>
  <% else %>
    <%= link_to place_went_to_gos_path(place.id), method: :post, remote: true do %>
      <div class="vertical_like">
        <i class="far fa-map"></i>
        <span class="grey-text text-darken-2">
          <%= place.went_to_gos.count %>
        </span>
      </div>
    <% end %>
  <% end %>

<% else %>

  <% if place.went_to_gos.count > 0 %>
    <div class="vertical_like">
      <i class="fas fa-map"></i>
      <span class="red-text">
        <%= place.went_to_gos.count %>
      </span>
    </div>
  <% else %>
    <div class="vertical_like">
      <i class="far fa-map"></i>
      <span class="grey-text text-darken-2">
        <%= place.went_to_gos.count %>
      </span>
    </div>
  <% end %>

<% end %>

app/views/went_to_gos/create.js.erb
$('#went-to-go-<%= @place.id %>').html("<%= j(render partial: 'went_to_gos/went_to_go', locals: {place: @place}) %>");

app/views/went_to_gos/destroy.js.erb
$('#went-to-go-<%= @place.id %>').html("<%= j(render partial: 'went_to_gos/went_to_go', locals: {place: @place}) %>");

app/views/went_to_gos/index.html.erb
<div class="container">
  <div class="section">
    <% if @places.empty? %>
      <div class="row">
        <% if @user == current_user %>
          <div class="center">
            <b>行きたいスポットがまだありません。</b><br>
            <%= link_to places_path do %>
              <b>探してみる！</b>
            <% end %>
          </div>
        <% end %>
        <div class="center">
          <b>行きたいスポットがまだありません。</b>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div id='map'></div>
      </div>
      <div class="row">
        <% @places.order(created_at: "DESC").each do |place| %>
          <div class="col s12 m6">
            <%= render partial: 'places/index', locals: {place: place} %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


<!-- スポットデータ受け渡し用 -->
<input name="spot_data" type="hidden" value=<%= @posts_data_json %> class="spot_data"/>

<style>
#map{
  height: 400px;
}
</style>

<!-- Googleマップを利用するためのスクリプト -->
<%= javascript_include_tag 'googlemap.js' %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>