config/routes.rb
Rails.application.routes.draw do

  root to: 'opens#top'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do 
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resources :went_to_gos, only: [:index]
  end
  resources :comments
  resources :places do
    resources :posts, only: [:new]
    resources :went_to_gos, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :posts
  # has_many :tag_for_palaces
  # belongs_to :category
  has_many :went_to_gos

  mount_uploaders :images, ImageUploader

   # 引数ユーザがこの場所に対して行ってみたいしてれば、そのwent_to_go_userを返す
  def went_to_go_user(user_id)
    went_to_gos.find_by(user_id: user_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable

  has_many :likes
  has_many :comments
  # has_many :tag_for_posts
  # has_many :equipments
  belongs_to :place
  belongs_to :user

  # 引数ユーザがこの投稿に対していいねしてるか
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  mount_uploaders :images, ImageUploader

  # バリデーション
  validates :title, presence: true
  validates :title, length: { in: 1..30 } 

  validates :user_id, presence: true
  validates :place_id, presence: true
  validates :images, presence: true
  validates :title, presence: true
  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"

  validates :following_id, presence: true
  validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :went_to_gos, dependent: :destroy

  has_many :following_relationships,foreign_key: "follower_id", class_name: "FollowRelationship",  dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships,foreign_key: "following_id",class_name: "FollowRelationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    self.followings.include?(other_user)
  end

  mount_uploader :profile_image, ImageUploader
  mount_uploader :back_image, ImageUploader

  # バリデーション
  validates :name, length: { in: 1..15 }

  validates :account_name, presence: true
  validates :account_name, format: { with: /\A[0-9a-zA-Z]+\z/ }
  validates :account_name, presence: true
  validates :account_name, uniqueness: true
  validates :account_name, length: { in: 1..15 } 


end

app/models/went_to_go.rb
class WentToGo < ApplicationRecord
  belongs_to :place
  belongs_to :user
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/opens_controller.rb
class OpensController < ApplicationController
  def top
    
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!

  def index

    # 投稿のあるPlaceのみ
    @places = Place.all
    array = []
    @places.each do |place|
      array.push(place.id) if place.posts.present?
    end
    @places = @places.where(id: array)

    @posts_data_arr = []
    @places.each do |place|
      @posts_data_arr.push({:id => place.id, :name => place.name, :lat => place.latitude, :lng => place.longitude})
    end
    @posts_data_json = @posts_data_arr.to_json.html_safe
  end

  def new
    @place = Place.new
    @categories = Category.all
  end

  def create
    place = Place.new(place_params)
    place.created_by = current_user.id
    place.is_delete = false
    place.save!
    redirect_to new_place_post_path(place)
  end

  def show
    @place = Place.find(params[:id])
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    place = Place.find(params[:id])
    place.update!(post_params)
    redirect_to place_path(place)
  end

  def destroy

  end

  private

  def place_params
    params.require(:place).permit(:name, :latitude, :longitude, :infomation, :address, :is_delete, :created_by, :category_id, {images: []})
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @places = Place.all
    @place = Place.find(params[:place_id])
    @post.place_id = @place.id
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      @place = @post.place
      @places = Place.all
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])

    # 投稿したユーザでない場合は更新不可
    if @post.user != current_user
      redirect_to user_path(current_user)
    end

    # 投稿のあるPlaceのみ
    @places = Place.all
    array = []
    @places.each do |place|
      array.push(place.id) if place.posts.present?
    end
    @places = @places.where(id: array)

    @place = @post.place
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      # 投稿のあるPlaceのみ
      @places = Place.all
      array = []
      @places.each do |place|
        array.push(place.id) if place.posts.present?
      end
      @places = @places.where(id: array)

      @place = @post.place

      render "edit"
    end
    
  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit(:title, :user_id, :place_id, :comment, :date, :time, :rate, :access, :notify, :url, :camera, :tag_list, {images: []})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    
    @like_count_array = @user.posts.map{|post| post.likes.count}
    @like_count = @like_count_array.sum
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end

  def followings
    @user =User.find(params[:id])
    @users =@user.followings.page(params[:page]).per(5)
    render 'show_followings'
  end

  def followers
    @user =User.find(params[:id])
    @users =@user.followers.page(params[:page]).per(5)
    render 'show_followers'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :address, :is_admin, :back_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opens_helper.rb
module OpensHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/went_to_gos_helper.rb
module WentToGosHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless post.like_user(current_user.id).blank? %>
    <%= link_to post_like_path(post_id: post.id ,id: post.like_user(current_user.id)), method: :delete, remote: true do %>
      <div class="vertical_like">
        <i class="fas fa-thumbs-up"></i>
        <span class="red-text">
          <%= post.likes.count %>
        </span>
      </div>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true do %>
      <div class="vertical_like">
        <i class="far fa-thumbs-up"></i>
        <span class="grey-text text-darken-2">
          <%= post.likes.count %>
        </span>
      </div>
    <% end %>
  <% end %>

<% else %>

  <% if post.likes.count > 0 %>
    <div class="vertical_like">
      <i class="fas fa-thumbs-up"></i>
      <span class="red-text">
        <%= post.likes.count %>
      </span>
    </div>
  <% else %>
    <div class="vertical_like">
      <i class="far fa-thumbs-up"></i>
      <span class="grey-text text-darken-2">
        <%= post.likes.count %>
      </span>
    </div>
  <% end %>

<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/places/_index.html.erb
<div class="card">
  <div class="card-image">
    <% if place.posts.present? %>
      <%= link_to place_path(place) do %>
        <%= image_tag place.posts.first.images[0].url, style: "object-fit: cover; height: 250px;" %>
      <% end %>
    <% end %>
    <span class="card-title">
      <i class="fas fa-map-marker-alt"></i> <%= place.name %>
    </span>
  </div>
  <div class="card-content" sytle="height: 250px;">
    <div id="went-to-go-<%= place.id %>" style="float: left;">
      <%= render partial: 'went_to_gos/went_to_go', locals: {place: place} %>
    </div>
    <div style="margin-left: 10px; display: inline-block;">
      <i class="fas fa-pen-nib"></i><%= " #{place.posts.count}" %>
    </div>

    <table>
      <tr>
        <th>
          最新の投稿
        </th>
        <td>
          <% if place.posts.last %>
            <p><%= place.posts.last.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H時%M分") %></p>
          <% end %>
        </td>
      </tr>
    </table>

  </div>
  <div class="card-action">
    <%= link_to "#{place.name}の投稿一覧をみる", place_path(place) %>
  </div>
</div>

app/views/places/index.html.erb
<!-- マップ -->
<div class="container">
  <div class="section">
    <div class="row">
      <div id='map'>
      </div>
    </div>
    <div class="row">
      <% @places.order(created_at: "DESC").each do |place| %>
        <div class="col s12 m6">
          <%= render partial: 'places/index', locals: {place: place} %>
        </div>
      <% end %>
    </div>
  </div>
</div>





<!-- スポットデータ受け渡し用 -->
<input name="spot_data" type="hidden" value=<%= @posts_data_json %> class="spot_data"/>

<style>
#map{
  height: 400px;
}
</style>

<!-- Googleマップを利用するためのスクリプト -->
<%= javascript_include_tag 'googlemap.js' %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

app/views/places/new.html.erb
<div class="section">
  <div class="container">
    <div id='map'></div>
  </div>
  <br>
  <div class="container">
    <%= form_with model: @place do |f| %>
      <%= f.hidden_field :latitude, value: 1, id: "set-latitude" %>
      <%= f.hidden_field :longitude, value: 1, id: "set-longitude" %>

      <div class="field">
        <%= f.label :name, "名称", class: "label" %>
        <%= f.text_field :name, id: "address", class: "input", id: "address" %>
      </div>
      <div class="control">
        <input type="button" value="見つける" onclick="codeAddress()" class="btn">
      </div>
      <br>
      <%= f.submit "この場所を登録する", class: "btn", id: "place-submit-button", disabled: "true" %>
  <% end %>
  </div>
</div>

<style>
#map{
  height: 400px;
}
</style>

<!-- Googleマップを利用するためのスクリプト -->
<%= javascript_include_tag 'new_place.js' %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

app/views/places/show.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center teal-text text-lighten-2"></h1>
      <div class="row center">
        <h1 class="header col s12 light"><%= @place.name %></h1>
      </div>
      <br><br>
    </div>
  </div>
  <div class="parallax img-wrap"><%= image_tag @place.posts.first.images[0].url, class:"img-position-center", style: "width: 100%; object-fit: contain;" %></div>
</div>

<div class="container">
  <h5 style="text-align: center;">
    <%= link_to new_place_post_path(@place), class: "button is-link" do %>
      <i class="fas fa-pencil-alt">この場所で投稿する</i>
    <% end %>
  </h5>
</div>

<%= render partial: 'posts/index', locals: {posts: @place.posts} %>

<script>
  (function($) {
    $(function() {

        $('.sidenav').sidenav();
        $('.parallax').parallax();

    }); // end of document ready
  })(jQuery); // end of jQuery name space
</script>

app/views/posts/_index.html.erb
<div class="container">
  <div class="section">
    <div class="row">
      <% posts.each do |post| %>
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image" style="">
              <%= link_to post_path(post) do %>
                <% if post.images[0] %>
                  <%= image_tag post.images[0].url, style: "height: 250px; object-fit: cover;" %>
                <% else %>
                  <%= image_tag "no_image.jpg", style: "height: 250px; object-fit: cover;" %>
                <% end %>
              <% end %>
              <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a> -->
            </div>
            <div class="card-content" style="height: 250px;">
              <%= link_to place_path(post.place) do %>
                <p><i class="fas fa-map-marker-alt"></i><b><%= " #{post.place.name}" %></b></p>
              <% end %>
              <%= link_to post_path(post) do %>
                <span class="card-title"><%= post.title %></span>
              <% end %>
              <p><%= post.comment.truncate(55) %></p>
              <div class="right">
                <i class="fas fa-comment">コメント数 <%= post.comments.count %></i>
              </div>
            </div>
            <div class="card-action" style="height: 60px;">
              <%= link_to user_path(post.user) do %>
                <%= image_tag post.user.profile_image.url, class: "is-rounded circle responsive-img", style: "width:30px; height: 30px; object-fit: cover; float: left;" %>
                <b><p style="margin: 0 5px; line-height: 28px; display: inline-block;"><%= post.user.name %></p></b>
              <% end %>
              <div style="float: right;">
              <i class="fas fa-pen-nib"></i><%= " #{post.user.posts.count}" %>
              <i class="fas fa-heart" style="padding-left: 4px;"></i><%= " #{Relationship.where(following_id: post.user.id).count}" %>
              <i class="fas fa-compass" style="padding-left: 4px;"></i><%= " #{post.user.went_to_gos.count}" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <div class="chip">
    <%= tag %>
  <!-- <i class="close material-icons">close</i> -->
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div style="margin-bottom: 0px;">
    <br>
    <%= form_with model: @post, local: true do |f| %>
      <h5><b><%= @post.place.name %></b><span style="font-size: 80%;">の投稿編集<span></h5>
      <%= f.hidden_field :place_id, :value => @post.place.id %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :title, class: "validate", id: "input_text" %>
          <%= f.label :title, "タイトル", class: "active" %>
          <span class="helper-text" data-error="wrong" data-success="right">1〜30字</span>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.date_field :date, class: "validate" %>
          <%= f.label :date, "訪問日", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.time_field :time, class: "validate" %>
          <%= f.label :time, "時間", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.select :rate, [["★", 1], ["★★", 2], ["★★★", 3], ["★★★★", 4], ["★★★★★", 5]], class: "" %>
          <%= f.label :rate, "オススメ度", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :access, class: "materialize-textarea" %>
          <%= f.label :access, "アクセス方法", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :notify, class: "materialize-textarea" %>
          <%= f.label :notify, "注意事項", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :url, class: "" %>
          <%= f.label :url, "参考URL", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :comment, class: "materialize-textarea" %>
          <%= f.label :comment, "コメント", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :camera, class: "materialize-textarea" %>
          <%= f.label :camera, "機材", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "materialize-textarea" %>
          <%= f.label :tag_list, "タグ", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <span class="">
            <i class="fas fa-upload"></i>
          </span>
          <span class="">
            <%= f.label :profile_image, "写真" %>
          </span>
          <span class="file-name">
              <%= f.file_field :images, multiple: true, class: "form-control-file" %>
          </span>
        </div>
      </div>
        
        <div class="input-field col s12">
          <%= f.button type: "submit", class: "btn waves-effect waves-light" do %>保存
            <!-- <i class="material-icons right">send</i> -->
          <% end %>
          <button class="btn">キャンセル</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render partial: 'posts/index', locals: {posts: @posts} %>

app/views/posts/new.html.erb
<div class="container">
  <div style="margin-bottom: 0px;">
    <br>
    <%= form_with model: @post, local: true do |f| %>
      <h5><b><%= @post.place.name %></b><span style="font-size: 80%;">の新規投稿<span></h5>
      <%= f.hidden_field :place_id, :value => @post.place.id %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :title, class: "" %>
          <%= f.label :title, "タイトル" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.date_field :date, class: "" %>
          <%= f.label :date, "訪問日", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.time_field :time, class: "" %>
          <%= f.label :time, "時間", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.select :rate, [["★", 1], ["★★", 2], ["★★★", 3], ["★★★★", 4], ["★★★★★", 5]], class: "" %>
          <%= f.label :rate, "オススメ度", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :access, class: "materialize-textarea" %>
          <%= f.label :access, "アクセス方法", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :notify, class: "materialize-textarea" %>
          <%= f.label :notify, "注意事項", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :url, class: "" %>
          <%= f.label :url, "参考URL", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :comment, class: "materialize-textarea" %>
          <%= f.label :comment, "コメント", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :camera, class: "materialize-textarea" %>
          <%= f.label :camera, "機材", class: "" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "" %>
          <%= f.label :tag_list, "タグ", class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <span class="">
            <i class="fas fa-upload"></i>
          </span>
          <span class="">
            <%= f.label :profile_image, "写真" %>
          </span>
          <span class="file-name">
              <%= f.file_field :images, multiple: true, class: "form-control-file" %>
          </span>
        </div>
      </div>
        
        <div class="input-field col s12">
          <%= f.button type: "submit", class: "btn waves-effect waves-light" do %>保存
            <!-- <i class="material-icons right">send</i> -->
          <% end %>
          <% if false %>
            <button class="button is-link is-light">Cancel</button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col m12">
      <h4>
        <%= @post.title %>
      </h4>
      <%= link_to place_path(@post.place) do %>
        <h5><i class="fas fa-map-marker-alt"></i><b><%= @post.place.name %></b></h5>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div style="justify-content: center;">
      <figure class="image">
        <div class="main_image_box">
          <%= image_tag @post.images[0].url, class: "mainimage img01", style: "max-height: 600px; min-height: 400px; width: 100%; object-fit: contain;" %>
        </div>	
      </figure>
    </div>
  </div>

  <div class="row">
    <ul class="subimage img01">
      <% @post.images.each do |image| %>
        <div class="col s3">
          <%= image_tag image.url, style: "width: 100%; object-fit: contain;" %>
        </div>
      <% end %>
    </ul>
  </div>

  <div class="divider"></div>

  <div class="row">
    <table class="striped">
      <tbody>
        <tr>
          <th>
            <span><i class="fas fa-calendar-alt"></i> 訪問日</span>
          </th>
          <td>
            <% if @post.date.present? %>
              <%= @post.date.strftime("%Y年%m月%d日 %a") %>
            <% end %>
            <% if @post.time.present? %>
              <span style="padding-left: 10px;">
                <%= @post.time.strftime("%H:%M %P") %>
              </span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <span><i class="fas fa-star"></i> オススメ度</span>
          </th>
          <td>
            <% case @post.rate.to_i %>
            <% when 1 %>
              ★
            <% when 2 %>
              ★★
            <% when 3 %>
              ★★★
            <% when 4 %>
              ★★★★
            <% when 5 %>
              ★★★★★
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <span><i class="fas fa-train"></i> アクセス</span>
          </th>
          <td>
            <%= @post.access %>
          </td>
        </tr>
        <tr>
          <th>
            <span><i class="fas fa-exclamation-circle"></i> 注意事項</span>
          </th>
          <td>
            <%= @post.notify %>
          </td>
        </tr>
        <tr>
          <th>
            <span><i class="fas fa-link"></i> URL</span>
          </th>
          <td>
            <%= link_to @post.url, @post.url %>
          </td>
        </tr>
        <tr>
          <th>
            <span><i class="fas fa-camera"></i> カメラ</span>
          </th>
          <td>
            <%= @post.camera %>
          </td>
        </tr>
        <tr>
          <th>
            <span><i class="fas fa-tags"></i> タグ</span>
          </th>
          <td>
            <%= render 'posts/tag_list', tag_list: @post.tag_list %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <p><%= @post.comment %></p>

  <div class="right" style="margin-bottom: 40px;">
    <%= link_to edit_post_path(@post) do %>
      <i class="fas fa-edit"></i>投稿内容を編集
    <% end %>
  </div>

  <table class="centered" style="table-layout: fixed;">
    <thead>
      <tr>
          <th>いいね</th>
          <th>行ってみたいスポット</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>
          <div id="likes_buttons_<%= @post.id %>">
            <%= render partial: 'likes/like', locals: {post: @post} %>
          </div>
        </td>
        <td>
          <div id="went-to-go-<%= @post.place.id %>">
            <%= render partial: 'went_to_gos/went_to_go', locals: {place: @post.place} %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="divider"></div>
  <h5>コメント</h5>
  <br>

  <div id="comment">
    <%= render partial: 'comments/index', locals: {post: @post, comment: @comment} %>
  </div>
</div>

<script>
$(function(){
    $('.subimage .col').hover(function(){
        //オーバーしたliのインデックスを取得
        var index = $('.subimage .col').index(this);

        //オーバーした画像URLを取得
        var imageurl = $('.subimage .col').eq(index).find('img').attr('src');

        //ulのクラス名を取得（空白で分割）
        className = $(this).parent().attr('class').split(" ");

        //元のメイン画像を保存しておく
        defaultImage = $('img.mainimage.'+className[1]).attr('src');

        $('img.mainimage.'+className[1]).attr('src',imageurl);
    },function(){
        $('img.mainimage.'+className[1]).attr('src',defaultImage);
    });
});
</script>



<style>
.detail {
  display: flex;
  justify-content: center;
}

.detail ul{
    
    text-align: center;
    
  
}
.detail li{

  display: -moz-inline-box;
  display: inline-block;
  /display: inline;
  /zoom: 1;
  width: 20%;

}


</style>