config/routes.rb
Rails.application.routes.draw do

  root to: 'opens#top'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do 
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resources :went_to_gos, only: [:index]
  end
  resources :comments
  resources :places do
    resources :posts, only: [:new]
    resources :went_to_gos, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :went_to_gos, dependent: :destroy

  has_many :following_relationships,foreign_key: "follower_id", class_name: "FollowRelationship",  dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships,foreign_key: "following_id",class_name: "FollowRelationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    self.followings.include?(other_user)
  end

  mount_uploader :profile_image, ImageUploader
  mount_uploader :back_image, ImageUploader

  # バリデーション
  validates :name, length: { in: 1..15 }

  validates :account_name, presence: true
  validates :account_name, format: { with: /\A[0-9a-zA-Z]+\z/ }
  validates :account_name, presence: true
  validates :account_name, uniqueness: true
  validates :account_name, length: { in: 1..15 } 


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    
    @like_count_array = @user.posts.map{|post| post.likes.count}
    @like_count = @like_count_array.sum
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end

  def followings
    @user =User.find(params[:id])
    @users =@user.followings.page(params[:page]).per(5)
    render 'show_followings'
  end

  def followers
    @user =User.find(params[:id])
    @users =@user.followers.page(params[:page]).per(5)
    render 'show_followers'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :address, :is_admin, :back_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <br>
  <%= form_with model: @user do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :name %>
        <%= f.label :name, "ユーザ名", class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :introduction, class: "materialize-textarea"  %>
        <%= f.label :introduction, "自己紹介", class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :address %>
        <%= f.label :address, "すんでいるところ", class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          <%= f.label :profile_image, "アイコン画像" %>
        </span>
        <span class="file-name">
          <%= f.file_field :profile_image %>
        </span>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          <%= f.label :profile_image, "背景画像" %>
        </span>
        <span class="file-name">
          <%= f.file_field :back_image %>
        </span>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12"> 
        <%= f.button type: "submit", class: "btn waves-effect waves-light" do %>保存<% end %>
        <button class="btn">キャンセル</button>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="section">
    <div class="row">
      <% @users.each do |user| %>
        <% next if user == current_user %>
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image" style="height: 200px;">
              <%= link_to user_path(user) do %>
                <%= image_tag user.back_image.url, style: "object-fit: cover; width: 100%; height: 100%;" %>
              <% end %>
              <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a> -->
            </div>
            <div class="card-content" style="height: 320px;">
              <div style="margin-bottom: 20px;">
                <%= link_to user_path(user) do %>
                  <%= image_tag user.profile_image.url, class: "is-rounded circle responsive-img", style: "width:70px; height: 70px; object-fit: cover; float: left; margin-right: 20px;" %>
                  <span class="card-title"><%= user.name %></span>
                <% end %>
                <%= link_to user_path(user) do %>
                  <p><i class="fas fa-map-marker-alt"></i><b><%= " #{user.account_name}" %></b></p>
                <% end %>
              </div>
              <div>
                <% if user.introduction.present? %>
                  <p><%= user.introduction.truncate(60) %></p>
                <% end %>
              </div>
              <div>
                <table class="centered" style="table-layout: fixed;">
                  <thead>
                    <tr>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td class="center-align">
                        <i class="fas fa-pen-nib"></i><%= " #{user.posts.count}" %>
                      </td>
                      <td class="center-align">
                        <i class="fas fa-heart" style="padding-left: 4px;"></i><%= " #{Relationship.where(following_id: user.id).count}" %>
                      </td>
                      <td class="center-align">
                        <i class="fas fa-compass" style="padding-left: 4px;"></i><%= " #{user.went_to_gos.count}" %>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      
      <% end %>
    
  </div>
</div>

app/views/users/show.html.erb
<div id="index-banner" class="parallax-container" style="z-index: 10;">
  <div class="section no-pad-bot">
    <div class="container">
      <% if false %>
      <br><br>
      <h1 class="header center teal-text text-lighten-2"></h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
      </div>
      <br><br>
      <% end %>
    </div>
  </div>
  <div class="parallax" style="z-index: 100;"><%= image_tag @user.back_image.url, style: "width: 100%; object-fit: contain;" %></div>
</div>

<div class="container">
  <div class="section">
    
    <div class="row">
        <div class="col s12 m3 center-on-small-only">
          <div class="image-container center">
            <% if @user.profile_image? %>
              <%= image_tag @user.profile_image.url, class: "circle user-show-user-img", style: "width: 150px; height: 150px;" %>
            <% end %>
          </div>
        </div>
        <div class="col s12 m9">
          <h4><b><%= @user.name %></b></h4>
          <h6>@<%= @user.account_name %></h6>
          <p class="light"><%= @user.introduction %></p>
          <div class="right">
            <% if @user == current_user %>
              <%= link_to edit_user_path(@user) do %>
                <i class="fas fa-edit"></i>プロフィールを編集
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="col s12" style="margin-top: 20px;">
          <table class="user-status-table" style="table-layout: fixed;">
            <tr>
              <th style="font-size: 80%;">
                <i class="fas fa-heart"></i><br>フォロワー
              </td>
              <th style="font-size: 80%;">
                <i class="fas fa-heart"></i><br>フォロー
              </th>
              <th style="font-size: 80%;">
                <i class="fas fa-pencil-alt"></i><br>投稿
              </th>
              <th style="font-size: 80%;">
                <i class="fas fa-map"></i><br>行きたい<br>スポット
              </th>
            </tr>
            <tr>
              <td class="icon-none">
                <div id="relationship-<%= @user.id %>">
                  <%= render 'relationships/follow', user: @user %>
                </div>
              </td>
              <td>
                <h5>
                  <%= Relationship.where(follower_id: @user.id).count %>
                </h5>
              </td>
              <td>
                <h5>
                  <%= @user.posts.count %>
                </h5>
              </td>
              <td>
                <h5>
                  <%= link_to user_went_to_gos_path(@user) do %>
                    <%= @user.went_to_gos.count %>
                  <% end %>
                </h5>
              </td>
            </tr>
          </table>
        </div>
      </div>

  </div>
</div>

<%= render partial: 'posts/index', locals: {posts: @posts} %>

<script>
  (function($) {
      $(function() {

          $('.sidenav').sidenav();
          $('.parallax').parallax();

      }); // end of document ready
  })(jQuery); // end of jQuery name space
</script>