config/routes.rb
Rails.application.routes.draw do

  root to: 'opens#top'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do 
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resources :went_to_gos, only: [:index]
  end
  resources :comments
  resources :places do
    resources :posts, only: [:new]
    resources :went_to_gos, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :posts
  # has_many :tag_for_palaces
  # belongs_to :category
  has_many :went_to_gos

  mount_uploaders :images, ImageUploader

   # 引数ユーザがこの場所に対して行ってみたいしてれば、そのwent_to_go_userを返す
  def went_to_go_user(user_id)
    went_to_gos.find_by(user_id: user_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable

  has_many :likes
  has_many :comments
  # has_many :tag_for_posts
  # has_many :equipments
  belongs_to :place
  belongs_to :user

  # 引数ユーザがこの投稿に対していいねしてるか
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  mount_uploaders :images, ImageUploader

  # バリデーション
  validates :title, presence: true
  validates :title, length: { in: 1..30 } 

  validates :user_id, presence: true
  validates :place_id, presence: true
  validates :images, presence: true
  validates :title, presence: true
  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"

  validates :following_id, presence: true
  validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :went_to_gos, dependent: :destroy

  has_many :following_relationships,foreign_key: "follower_id", class_name: "FollowRelationship",  dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships,foreign_key: "following_id",class_name: "FollowRelationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    self.followings.include?(other_user)
  end

  mount_uploader :profile_image, ImageUploader
  mount_uploader :back_image, ImageUploader

  # バリデーション
  validates :name, length: { in: 1..15 }

  validates :account_name, presence: true
  validates :account_name, format: { with: /\A[0-9a-zA-Z]+\z/ }
  validates :account_name, presence: true
  validates :account_name, uniqueness: true
  validates :account_name, length: { in: 1..15 } 


end

app/models/went_to_go.rb
class WentToGo < ApplicationRecord
  belongs_to :place
  belongs_to :user
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/opens_controller.rb
class OpensController < ApplicationController
  def top
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @places = Place.all
    @place = Place.find(params[:place_id])
    @post.place_id = @place.id
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      @place = @post.place
      @places = Place.all
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])

    # 投稿したユーザでない場合は更新不可
    if @post.user != current_user
      redirect_to user_path(current_user)
    end

    # 投稿のあるPlaceのみ
    @places = Place.all
    array = []
    @places.each do |place|
      array.push(place.id) if place.posts.present?
    end
    @places = @places.where(id: array)

    @place = @post.place
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      # 投稿のあるPlaceのみ
      @places = Place.all
      array = []
      @places.each do |place|
        array.push(place.id) if place.posts.present?
      end
      @places = @places.where(id: array)

      @place = @post.place

      render "edit"
    end
    
  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit(:title, :user_id, :place_id, :comment, :date, :time, :rate, :access, :notify, :url, :camera, :tag_list, {images: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opens_helper.rb
module OpensHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/went_to_gos_helper.rb
module WentToGosHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <div class="row">
      <div class="col s12">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">アラート</span>
            <ul>
              <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSpotInfoSharingApp</title>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'materialize-jquery.js' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <!-- ログイン時のnavセレクトボックス -->
    <% if user_signed_in? %>
    <ul id="dropdown1" class="dropdown-content">
      <li>
        <%= link_to new_place_path do %>
          <span style="font-size: 80%;">投稿する</span>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to user_path(current_user) do %>
          <span style="font-size: 80%;">マイページ</span>
        <% end %>
      </li>
      <li>
        <%= link_to user_went_to_gos_path(current_user) do %>
          <span style="font-size: 80%;">行きたい<br>スポット</span>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to  destroy_user_session_path, method: :delete do %>
          <span style="font-size: 80%;">ログアウト</span>
        <% end %>
      </li>
    </ul>
    <% end %>
    <nav class="white">
      <div class="nav-wrapper">
        <%= link_to root_path, class: "brand-logo" do %>
          <%= image_tag "fotopo_logo.png", alt: "FOTOPO icon", id: "pic1", class: "brand-logo", style: "width: 250px; margin: 11px;" %>
        <% end %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      
        <%# ↓brand-logoクラスをつけないとuser/showなどの画像表示が崩れる %>
        <ul class="right hide-on-med-and-down brand-logo">
          <% if user_signed_in? %>
            <li>
              <%= link_to places_path do %>
                <i class="fas fa-map-marker-alt"></i>スポット
              <% end %>
            </li>
            <li>
              <%= link_to posts_path do %>
                <i class="fas fa-clipboard"></i>投稿
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: "navbar-item"  do %>
                <i class="fas fa-user-friends"></i>ユーザー
              <% end %>
            </li>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
          <% else %>
            <li>
              <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt"></i></i>ログイン
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
              <i class="fas fa-user-plus"></i></i>新規登録
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- モバイルのnav -->
    <ul id="mobile-demo" class="sidenav">
      <% if user_signed_in? %>
        <li>
          <%= link_to places_path do %>
            <i class="fas fa-map-marker-alt"></i>スポットを探す
          <% end %>
        </li>
        <li>
          <%= link_to posts_path do %>
            <i class="fas fa-clipboard"></i>投稿を探す
          <% end %>
        </li>
        <li>
          <%= link_to users_path, class: "navbar-item"  do %>
            <i class="fas fa-user-friends"></i>ユーザーを探す
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to user_path(current_user) do %>
            <div class="chip" style="">
              <%= image_tag current_user.profile_image.url, alt: "Contact Person", class: "circle", style: "width:32px; height: 32px; object-fit: cover;" %>
              <%= current_user.name %>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to new_place_path, class: "navbar-item" do %>
            <i class="fas fa-pencil-alt"></i>投稿する
          <% end %>
        </li>
        <li>
          <%= link_to user_went_to_gos_path(current_user) do %>
            <i class="fas fa-map"></i>行きたいスポット
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i>ログアウト
          <% end %>
        </li>
      </ul>
      <% else %>
        <li>
          <%= link_to root_path do %>
          <i class="fas fa-question-circle"></i>fotopoとは？
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path do %>
          <i class="fas fa-user-plus"></i></i>新規登録
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
          <i class="fas fa-sign-in-alt"></i></i>ログイン
          <% end %>
        </li>
      <% end %>
    </ul>
  </ul>
    <main>
    <%= yield %>
    </main>
  
    <footer class="page-footer teal lighten-3">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">fotopo</h5>
            <p class="grey-text text-lighten-4">「好きな場所」をシェアしよう！</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2020 YAC
        <a class="grey-text text-lighten-4 right" href="https://yac-photo.net/">YACのWebサイト</a>
        </div>
      </div>
    </footer>
  </body>
  
  
</html>